### ISSUE TITLE
Unable to install this module

### ISSUE THREAD

**Issue by skptricks** [oransel/node-talib#112]
![image](https://github.com/user-attachments/assets/68ab700f-588e-4f71-bf6f-d598c78ed8c0)

Showing above error message while installation

**Comment by skptricks** [comment]
yes manually installed.

**Comment by oransel** [comment]
What's in the directory that it says can't find?
Is it there at all?
Keep in mind this hasn't been tested with the latest .NET frameworks.
If all fails, please use the [Windows Build Tools 2015](https://www.npmjs.com/package/windows-build-tools) as stated in the instructions.

**Comment by skptricks** [comment]
Nothing present in that directory.

I am getting below error while installing build tool 2015

`Error Message`
npm install --global windows-build-tools
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm warn deprecated windows-build-tools@5.2.2: Node.js now includes build tools for Windows. You probably no longer need this tool. See https://github.com/felixrieseberg/windows-build-tools for details.
npm warn cleanup Failed to remove some directories [
npm warn cleanup   [
npm warn cleanup     '\\\\?\\C:\\Users\\sumit\\AppData\\Roaming\\nvm\\v22.12.0\\node_modules\\windows-build-tools\\node_modules\\object-keys',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\sumit\AppData\Roaming\nvm\v22.12.0\node_modules\windows-build-tools\node_modules\object-keys\test'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\sumit\\AppData\\Roaming\\nvm\\v22.12.0\\node_modules\\windows-build-tools\\node_modules\\object-keys\\test'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     '\\\\?\\C:\\Users\\sumit\\AppData\\Roaming\\nvm\\v22.12.0\\node_modules\\windows-build-tools\\node_modules\\single-line-log',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\sumit\AppData\Roaming\nvm\v22.12.0\node_modules\windows-build-tools\node_modules\single-line-log\node_modules\is-fullwidth-code-point'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\sumit\\AppData\\Roaming\\nvm\\v22.12.0\\node_modules\\windows-build-tools\\node_modules\\single-line-log\\node_modules\\is-fullwidth-code-point'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     '\\\\?\\C:\\Users\\sumit\\AppData\\Roaming\\nvm\\v22.12.0\\node_modules\\windows-build-tools\\node_modules\\nugget',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\sumit\AppData\Roaming\nvm\v22.12.0\node_modules\windows-build-tools\node_modules\nugget'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\sumit\\AppData\\Roaming\\nvm\\v22.12.0\\node_modules\\windows-build-tools\\node_modules\\nugget'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     'C:\\Users\\sumit\\AppData\\Roaming\\nvm\\v22.12.0\\node_modules\\windows-build-tools',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\sumit\AppData\Roaming\nvm\v22.12.0\node_modules\windows-build-tools\node_modules\uri-js'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\sumit\\AppData\\Roaming\\nvm\\v22.12.0\\node_modules\\windows-build-tools\\node_modules\\uri-js'
npm warn cleanup     }
npm warn cleanup   ],
npm warn cleanup   [
npm warn cleanup     '\\\\?\\C:\\Users\\sumit\\AppData\\Roaming\\nvm\\v22.12.0\\node_modules\\windows-build-tools',
npm warn cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\sumit\AppData\Roaming\nvm\v22.12.0\node_modules\windows-build-tools\node_modules\verror'] {
npm warn cleanup       errno: -4048,
npm warn cleanup       code: 'EPERM',
npm warn cleanup       syscall: 'rmdir',
npm warn cleanup       path: 'C:\\Users\\sumit\\AppData\\Roaming\\nvm\\v22.12.0\\node_modules\\windows-build-tools\\node_modules\\verror'
npm warn cleanup     }
npm warn cleanup   ]
npm warn cleanup ]
npm error code 1
npm error path C:\Users\sumit\AppData\Roaming\nvm\v22.12.0\node_modules\windows-build-tools
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c node ./dist/index.js
npm error Downloading python-2.7.15.amd64.msi
npm error [>                                            ] 0.0% (0 B/s)
npm error ^[[1000D^[[0K^[[1A^[[1000D^[[0K^[[1A^[[1000D^[[0KDownloading python-2.7.15.amd64.msi
npm error [============================================>] 100.0% (0 B/s)
npm error ^[[1000D^[[0K^[[1A^[[1000D^[[0K^[[1A^[[1000D^[[0KDownloading python-2.7.15.amd64.msi
npm error [============================================>] 100.0% (0 B/s)
npm error Downloaded python-2.7.15.amd64.msi. Saved to C:\Users\sumit\.windows-build-tools\python-2.7.15.amd64.msi.
npm error
npm error
npm error ^[[1000D^[[0K^[[1A^[[1000D^[[0K^[[1A^[[1000D^[[0KDownloading vs_BuildTools.exe
npm error [>                                            ] 0.0% (0 B/s)
npm error ^[[1000D^[[0K^[[1A^[[1000D^[[0K^[[1A^[[1000D^[[0KDownloading vs_BuildTools.exe
npm error [============================================>] 100.0% (0 B/s)
npm error ^[[1000D^[[0K^[[1A^[[1000D^[[0K^[[1A^[[1000D^[[0KDownloading vs_BuildTools.exe
npm error [============================================>] 100.0% (0 B/s)
npm error Downloaded vs_BuildTools.exe. Saved to C:\Users\sumit\.windows-build-tools\vs_BuildTools.exe.
npm error
npm error Starting installation...
npm error Downloading installers failed. Error: TypeError: 'process.env' only accepts a configurable, writable, and enumerable data descriptor
npm error     at Function.defineProperty (<anonymous>)
npm error     at Object.removePath (C:\Users\sumit\AppData\Roaming\nvm\v22.12.0\node_modules\windows-build-tools\dist\utils\remove-path.js:11:12)
npm error     at Object.install (C:\Users\sumit\AppData\Roaming\nvm\v22.12.0\node_modules\windows-build-tools\dist\install\index.js:29:19)
npm error     at C:\Users\sumit\AppData\Roaming\nvm\v22.12.0\node_modules\windows-build-tools\dist\start.js:17:19
npm error     at Object.download (C:\Users\sumit\AppData\Roaming\nvm\v22.12.0\node_modules\windows-build-tools\dist\download.js:35:5)
npm error     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
npm error     at async Object.aquireInstallers (C:\Users\sumit\AppData\Roaming\nvm\v22.12.0\node_modules\windows-build-tools\dist\aquire-installers.js:32:13) {
npm error   code: 'ERR_INVALID_OBJECT_DEFINE_PROPERTY'
npm error }
npm error windows-build-tools will now exit.
npm error (node:8208) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm error (Use `node --trace-deprecation ...` to show where the warning was created)
npm error A complete log of this run can be found in: C:\Users\sumit\AppData\Local\npm-cache\_logs\2024-12-16T16_27_48_308Z-debug-0.log

**Comment by oransel** [comment]
Run it with `--vs2015`
You will need to resolve these as I don't suspect an issue with the library. I don't provide tech support.
