### ISSUE TITLE
require('talib') parse error

### ISSUE THREAD

**Issue by LeoAlvarez** [oransel/node-talib#32]
After installing with 
    npm install talib
and requiring (with     
    talib: require('talib')
 in a browserify project, i'm getting:

Error: Parsing file /Users/leo/devel/pscharts/node_modules/talib/build/Release/talib.node: Unexpected character '�' (1:0)
    at Deps.parseDeps (/usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:437:28)
    at fromSource (/usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:375:48)
    at /usr/local/lib/node_modules/browserify/node_modules/module-deps/index.js:370:17
    at ConcatStream.<anonymous> (/usr/local/lib/node_modules/browserify/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:460:14)
    at endWritable (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:469:3)
    at ConcatStream.Writable.end (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_writable.js:436:5)
    at DuplexWrapper.onend (/usr/local/lib/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:537:10)

**Comment by oransel** [comment]
can you submit a sample application to replicate issue?
