### ISSUE TITLE
Runtime Error In Alpine Linux with Node 0.12.14

### ISSUE THREAD

**Issue by lewisdawson** [oransel/node-talib#36]
I'm compiling my Node app into an [Alpine Linux Node Docker image (0.12.14)](https://github.com/mhart/alpine-node). The Docker image builds successfully with the following Docker configuration:

```
FROM mhart/alpine-node:0.12.14

# Copy the application over here...

RUN cd /opt/myapp \
    && apk add --update --no-cache \
        python \
        make \
        g++ \
    && npm install --production \
    && npm run postinstall \
    && apk del \
        python \
        make \
        g++

# Unrelated configuration below...
```

The build output of linux libs and talib 0.6.0 is as follows:

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.3/community/x86_64/APKINDEX.tar.gz
(1/25) Installing binutils-libs (2.25.1-r0)
(2/25) Installing binutils (2.25.1-r0)
(3/25) Installing gmp (6.1.0-r0)
(4/25) Installing isl (0.14.1-r0)
(5/25) Installing libgomp (5.3.0-r0)
(6/25) Installing libatomic (5.3.0-r0)
(7/25) Installing pkgconf (0.9.12-r0)
(8/25) Installing pkgconfig (0.25-r1)
(9/25) Installing mpfr3 (3.1.2-r0)
(10/25) Installing mpc1 (1.0.3-r0)
(11/25) Installing gcc (5.3.0-r0)
(12/25) Installing musl-dev (1.1.12-r5)
(13/25) Installing libc-dev (0.7-r0)
(14/25) Installing g++ (5.3.0-r0)
(15/25) Installing make (4.1-r0)
(16/25) Installing libbz2 (1.0.6-r4)
(17/25) Installing expat (2.1.1-r0)
(18/25) Installing libffi (3.2.1-r2)
(19/25) Installing gdbm (1.11-r1)
(20/25) Installing ncurses-terminfo-base (6.0-r6)
(21/25) Installing ncurses-terminfo (6.0-r6)
(22/25) Installing ncurses-libs (6.0-r6)
(23/25) Installing readline (6.3.008-r4)
(24/25) Installing sqlite-libs (3.9.2-r0)
(25/25) Installing python (2.7.11-r3)
Executing busybox-1.24.1-r7.trigger

> talib@0.6.0 install /opt/myapp/node_modules/talib
> node ./src/lib/build.js && node-gyp configure && node-gyp build

building talib functions...
make: Entering directory '/opt/myapp/node_modules/talib/build'
  CXX(target) Release/obj.target/talib/src/talib.o
  SOLINK_MODULE(target) Release/obj.target/talib.node
  COPY Release/talib.node
make: Leaving directory '/opt/myapp/node_modules/talib/build'
```

When I run the image inside a container, I get the following error:

```
Error: Error relocating /opt/myapp/node_modules/talib/build/Release/talib.node: TA_AVGDEV_Lookback: symbol not found
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/myapp/src/calc/calculator.js:5:13)
```

The same app built inside of the [docker node image](https://github.com/nodejs/docker-node/blob/6778e14c0c1ae53cc413f77a94c21c7cf05f651f/0.12/Dockerfile) runs fine. Any ideas on why this could be occurring?

**Comment by oransel** [comment]
Please try alpine-node v4, v4.4, or v4.4.4 with talib@1.0.2

**Comment by lewisdawson** [comment]
@oransel Unfortunately it results in the same error. Perhaps I'm missing a optional library during compile time or it's not detecting the OS properly during compile time? Any additional ideas? I see that the symbol it's failing to find resides inside a [conditional definition statement](https://github.com/oransel/node-talib/blob/master/src/lib/src/ta_func/ta_AVGDEV.c#L85):

```c++
/* Generated */ #define TA_PREFIX(x) TA_##x
/* Generated */ #define INPUT_TYPE   double
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */ int Core::AvgDevLookback( int           optInTimePeriod )  /* From 2 to 100000 */
/* Generated */ 
/* Generated */ #elif defined( _JAVA )
/* Generated */ public int avgDevLookback( int           optInTimePeriod )  /* From 2 to 100000 */
/* Generated */ 
/* Generated */ #else
/* Generated */ int TA_AVGDEV_Lookback( int           optInTimePeriod )  /* From 2 to 100000 */
/* Generated */ 
/* Generated */ #endif
```

**Comment by lewisdawson** [comment]
Here's the stack trade from the 4.4.4 version of Node and Alpine Linux:

```
Error: Error relocating /opt/gapper/node_modules/talib/build/Release/talib.node: TA_AVGDEV_Lookback: symbol not found
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by oransel** [comment]
I just tried with node v4.4.4 and compiled fine. I ran the examples and they worked too. I am not too familiar with the docker image you are referring to. It seems like the node extension is not build with linking against the TA-LIB. Is it complaining during compilation?

**Comment by lewisdawson** [comment]
@oransel Yea, I'm not super familiar with the Alpine Linux image either. I wanted to give it a try since it cuts my Docker image to 1/7 the size, which is awesome -- if it worked of course.

I don't see any compilation errors. It's the same output as I pasted earlier, just different talib version:

```
> talib@1.0.2 install /opt/myapp/node_modules/talib
> node ./src/lib/build.js && node-gyp configure && node-gyp build

building talib functions...
make: Entering directory '/opt/myapp/node_modules/talib/build'
  CXX(target) Release/obj.target/talib/src/talib.o
  SOLINK_MODULE(target) Release/obj.target/talib.node
  COPY Release/talib.node
make: Leaving directory '/opt/myapp/node_modules/talib/build'
```

Are there any additional compilation packages you're aware of that I may be needing to use?

**Comment by oransel** [comment]
Not all all. It should work as expected but not sure what the docker image does actually. I'll take a look at it when there is a chance.

**Comment by lewisdawson** [comment]
@oransel Alpine Linux is a very minimalistic Linux distro that focused on delivering small Docker images. The node version is just Alpine Linux with node on top of it, nothing fancy.

Did you mean to close this issue?

**Comment by oransel** [comment]
can you share a sample dockerfile?

**Comment by lewisdawson** [comment]
@oransel I'll put one together for you. I likely won't get posted until this weekend. Thanks for the help!

**Comment by TimPchelintsev** [comment]
Same issue...

**Comment by sohailalam2** [comment]
Hi @lewisdawson did you ever manage to fix or get around this issue?

**Comment by lewisdawson** [comment]
@sohailalam2 I don't believe I ever got this resolved. Sorry!
