### ISSUE TITLE
Failed installation on Windows 10

### ISSUE THREAD

**Issue by paaax** [oransel/node-talib#60]
Hey there,

I'm trying to install TALib on a windows machine. Therefore I installed windows-build-tools.

`npm install -g windows-build-tools`

If I then continue and run `npm install talib` from my project folder it shows the following error:
```

> talib@1.0.4 install C:\Users\xxx\Documents\xxx\node_modules\talib
> node ./src/lib/build.js && node-gyp configure && node-gyp build

building talib functions...
fs.js:928
  return binding.readdir(pathModule.toNamespacedPath(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework'
    at Object.fs.readdirSync (fs.js:928:18)
    at Object.<anonymous> (C:\Users\xxx\Documents\xxx\node_modules\talib\src\lib\build.js:22:30)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:660:3
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\xxx\Documents\xxx\package.json'
npm WARN Bot No description
npm WARN Bot No repository field.
npm WARN Bot No README data
npm WARN Bot No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! talib@1.0.4 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talib@1.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in: xxx
```
How can I solve this issue?

**Comment by oransel** [comment]
Can you install Microsoft .NET if you don't have it installed on your system already?

**Comment by paaax** [comment]
I took another route and installed Bash on Windows 10. In Bash everything worked as expected.
