### ISSUE TITLE
How to install node-talib on FreeBSD?

### ISSUE THREAD

**Issue by xFFFFF** [oransel/node-talib#62]
How to install or port node-talib on FreeBSD?
```
[root@dsadas:~/gekko/trade# npm install --save-exact talib 
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for talib@1.0.4: wanted {"os":"darwin,linux,win32","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux,win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   freebsd
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-22T18_40_31_053Z-debug.log
```

I changed linux to FreeBSD in packages.json file and run npm install:
```
npm WARN lifecycle talib@1.0.4~install: cannot run in wd %s %s (wd=%s) talib@1.0.4 node ./src/lib/build.js && node-gyp configure && node-gyp build /root/gekko/trade/node-talib
npm WARN talib@1.0.4 No license field.

up to date in 0.104s
```

**Comment by xFFFFF** [comment]
Anyone?

More logs
```
478 verbose stack Error: Unsupported platform for talib@1.0.4: wanted {"author":{"name":"Mustafa Oransel"},"contributors":[{"name":"Alfred Omega"},{"name":"Vedran Opacic"},{"name":"Kelvin Foo"},{"name":"Chris McGee"},{"name":"Marek Magdziak"}],"name":"talib","description":"Technical Analysis Library","version":"1.0.4","homepage":"https://github.com/oransel/node-talib","repository":{"type":"git","url":"git+https://github.com/oransel/node-talib.git"},"os":["darwin","linux","win32"],"scripts":{"install":"node ./src/lib/build.js && node-gyp configure && node-gyp build","clean":"node ./src/lib/clean.js"},"main":"build/Release/talib.node","engines":{"node":">=4.1.1"},"dependencies":{"nan":"^2.5.0"},"devDependencies":{},"optionalDependencies":{},"keywords":["talib","stocks","stock market"],"licenses":[{"type":"LGPL License","url":"http://www.gnu.org/licenses/lgpl.html"}],"_resolved":"https://registry.npmjs.org/talib/-/talib-1.0.4.tgz","_integrity":"sha512-s4QITrKVUZ4feHl78296sMKLRWBG8dbuBPE0nr8NHVJimzrz1GVI27PBfBHlx0Bx1+Bmu8/6IbQM+84x0B0eKQ==","_from":"talib@^1.0.4","bugs":{"url":"https://github.com/oransel/node-talib/issues"},"_id":"talib@1.0.4","bundleDependencies":false,"deprecated":false,"_shasum":"15643350bbf29cfea3b78c32cea80f5ed22a5da6","_requested":{"type":"range","registry":true,"raw":"talib@^1.0.4","name":"talib","escapedName":"talib","rawSpec":"^1.0.4","saveSpec":null,"fetchSpec":"^1.0.4"},"_spec":"talib@^1.0.4","_where":"/root/gekko/trade"} (current: {"os":"freebsd","cpu":"x64"})
478 verbose stack     at checkPlatform (/usr/local/lib/node_modules/npm/node_modules/npm-install-checks/index.js:45:14)
478 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
478 verbose stack     at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
478 verbose stack     at readJson.then.catch.then (/usr/local/lib/node_modules/npm/lib/install/action/refresh-package-json.js:31:12)
478 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
478 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
478 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
478 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
478 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
478 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
478 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:582:21)
478 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
478 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
478 verbose stack     at Promise._fulfill (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
478 verbose stack     at Promise._resolveCallback (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:432:57)
478 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:524:17)
479 verbose pkgid talib@1.0.4
480 verbose cwd /root/gekko/trade
481 verbose FreeBSD 10.3-RELEASE-p18
482 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "talib"
483 verbose node v9.7.1
484 verbose npm  v5.7.1
485 error code EBADPLATFORM
486 error notsup Unsupported platform for talib@1.0.4: wanted {"os":"darwin,linux,win32","arch":"any"} (current: {"os":"freebsd","arch":"x64"})
487 error notsup Valid OS:    darwin,linux,win32
487 error notsup Valid Arch:  any
487 error notsup Actual OS:   freebsd
487 error notsup Actual Arch: x64
488 verbose exit [ 1, true ]
```

Ta-lib library ( port for FreeBSD: https://svnweb.freebsd.org/ports/head/devel/ta-lib/ ) is installing on FreeBSD without problems. Only with node module I have problems.
