### ISSUE TITLE
Cannot install on windows 10

### ISSUE THREAD

**Issue by jslok** [oransel/node-talib#73]
Any help would be appreciated to solve this issue. Thank you

npm version 6.5.0
I have installed windows build tools for vs 2015

`C:\Users\jlok\Documents\Trading\p1>npm install --save talib

> talib@1.0.6 install C:\Users\jlok\Documents\Trading\p1\node_modules\talib
> node ./src/lib/build.js && node-gyp configure && node-gyp build

building talib functions...
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 1/12/2019 8:53:30 PM.
Project "C:\Users\jlok\Documents\Trading\p1\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "csr|x64".
Project "C:\Users\jlok\Documents\Trading\p1\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" (1) is building "C:\Users\jlok\Documents\Trading\p1\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_common\ta_common.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory ".\..\..\..\..\..\temp\csr\ta_common\".
  Creating directory ".\..\..\..\..\..\temp\csr\ta_common\ta_common.tlog\".
InitializeBuildStatus:
  Creating ".\..\..\..\..\..\temp\csr\ta_common\ta_common.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  CL.exe /c /I..\..\..\..\..\include /I..\..\..\..\..\src\ta_common\imatix\sfl /I..\..\..\..\..\src\ta_common /I..\..\..\..\..\src\ta_common\mt /Zi /nologo /W3 /WX /O2 /Ob1 /D NO_DEBUG /D NDEBUG /D WIN32 /D _MBCS /D _LIB /D QT_THREAD_SUPPORT /D _VC80_UPGRADE=0x0600 /D _MBCS /GF /Gm- /EHsc /MT /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo".\..\..\..\..\..\temp\csr\ta_common/" /Fd".\..\..\..\..\..\temp\csr\ta_common/ta_common.pdb" /Gd /TC /errorReport:queue ..\..\..\..\..\src\ta_common\ta_global.c ..\..\..\..\..\src\ta_common\ta_retcode.c ..\..\..\..\..\src\ta_common\ta_version.c
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\jlok\Documents\Trading\p1\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_common\ta_common.vcxproj]

Done Building Project "C:\Users\jlok\Documents\Trading\p1\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_common\ta_common.vcxproj" (default targets) -- FAILED.
Project "C:\Users\jlok\Documents\Trading\p1\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" (1) is building "C:\Users\jlok\Documents\Trading\p1\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_libc\ta_libc.vcxproj" (5) on node 1 (default targets).
PrepareForNMakeBuild:
  Creating directory ".\..\..\..\..\..\temp\csr\ta_libc\".
Done Building Project "C:\Users\jlok\Documents\Trading\p1\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_libc\ta_libc.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\Users\jlok\Documents\Trading\p1\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" (default targets) -- FAILED.

Build FAILED.

"C:\Users\jlok\Documents\Trading\p1\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" (default target) (1) ->
"C:\Users\jlok\Documents\Trading\p1\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_common\ta_common.vcxproj" (default target) (2) ->
(ClCompile target) ->
  TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\jlok\Documents\Trading\p1\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_common\ta_common.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.46

C:\Users\jlok\Documents\Trading\p1\node_modules\talib>if not defined npm_config_node_gyp (node "C:\Users\jlok\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure )  else (node "C:\Users\jlok\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure )

C:\Users\jlok\Documents\Trading\p1\node_modules\talib>if not defined npm_config_node_gyp (node "C:\Users\jlok\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build )  else (node "C:\Users\jlok\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" build )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\Users\jlok\Documents\Trading\p1\node_modules\talib\build\talib.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\jlok\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jlok\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\Users\jlok\Documents\Trading\p1\node_modules\talib
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN p1@1.0.0 No description
npm WARN p1@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! talib@1.0.6 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talib@1.0.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jlok\AppData\Roaming\npm-cache\_logs\2019-01-13T04_53_33_935Z-debug.log`

**Comment by jslok** [comment]
Solved this issue by creating a project in VS which installed some additional components.
https://stackoverflow.com/a/38387213
