### ISSUE TITLE
Error when npm install talib on windows10

### ISSUE THREAD

**Issue by peipeiTu** [oransel/node-talib#80]
I do have installed the Windows Build Tools.
But:
```
D:\intchains\quant-data\node_modules\talib>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_global\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build )  else (node "D:\Program Files\nodejs\node_global\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" build )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  talib.cpp
  win_delay_load_hook.cc
C:\Users\PeipeiTu\.node-gyp\10.2.0\include\node\node.h(53): fatal error C1083: Cannot open include file: 'core.h': No such file or directory (compiling source file ..\src\talib.cpp) [D:\intchains\quant-data\node_modules\talib\build\tali
b.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_global\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_global\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd D:\intchains\quant-data\node_modules\talib
gyp ERR! node -v v10.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! talib@1.0.7 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talib@1.0.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program Files\nodejs\node_cache\_logs\2019-05-30T01_34_51_410Z-debug.log
```
Can someone help me? Thanks a lot!

**Comment by Deca** [comment]
Same issue here, have you manage to solve it?

**Comment by Tupeipei** [comment]
@Deca No. I didn't solve it. I just did it by changing to use ubuntu.

**Comment by amangqq** [comment]
大佬解决了吗？我安装了windows-build-tools、NET Framework 4.6 Targeting Pack；[参照这个](https://github.com/oransel/node-talib/issues/77)，但是没啥用
