### ISSUE TITLE
Build issue Win 10: Fatal error LNK1181: cannot open input file '..\src\lib\lib\ta_libc_csr.lib'

### ISSUE THREAD

**Issue by tvdaredevil** [oransel/node-talib#86]
Hello there!
I am attempting to install the node-talib wrapper onto my Win 10, 64 bit computer. I am having a lot of trouble with installing this and I have scoured the web and could find no solution other than installing this in a UNIX environment. 

I ensured that I completed the proper prerequisites.
This is how far the build gets when I run ```npm i talib```:
```
building talib functions...
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 7/20/2020 9:57:06 PM.
Project "D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "csr|x64".
Project "D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" (1) is building "D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_common\ta_common.vcxproj" (2) on node 1 (default targets).
D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_common\ta_common.vcxproj(151,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargetsMicrosoft.CPP.UpgradeFromVC60.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_common\ta_common.vcxproj" (default targets) -- FAILED.
Project "D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" (1) is building "D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_func\ta_func.vcxproj" (3) on node 1 (default targets).
D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_func\ta_func.vcxproj(135,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargetsMicrosoft.CPP.UpgradeFromVC60.props" was not found. Confirm that the path in 
the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_func\ta_func.vcxproj" (default targets) -- FAILED.Project "D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" (1) is building "D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_abstract\ta_abstract.vcxproj" (4) on node 1 (default targets).
D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_abstract\ta_abstract.vcxproj(128,5): error MSB4019: The imported project 
"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargetsMicrosoft.CPP.UpgradeFromVC60.props" was not found. Confirm that the 
path in the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_abstract\ta_abstract.vcxproj" (default targets) -- FAILED.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.props(31,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Makefile.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.cpp.props (31,3)". This is most likely a build authoring error. This subsequent import will be ignored. [D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_libc\ta_libc.vcxproj]
Project "D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" (1) is building "D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_libc\ta_libc.vcxproj" (5) on node 1 (default targets).
D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_libc\ta_libc.vcxproj(136,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargetsMicrosoft.CPP.UpgradeFromVC60.props" was not found. Confirm that the path in 
the <Import> declaration is correct, and that the file exists on disk.
Done Building Project "D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_libc\ta_libc.vcxproj" (default targets) -- FAILED.Done Building Project "D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" (default targets) -- FAILED.

Build FAILED.

  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.props(31,3): warning MSB4011: "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Makefile.props" cannot be imported again. It was already imported at "C:\Program 
Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.cpp.props (31,3)". This is most likely a build authoring error. This subsequent import will be ignored. [D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_libc\ta_libc.vcxproj]


"D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" (default target) (1) ->
"D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_common\ta_common.vcxproj" (default target) (2) ->
  D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_common\ta_common.vcxproj(151,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargetsMicrosoft.CPP.UpgradeFromVC60.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.


"D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" (default target) (1) ->
"D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_func\ta_func.vcxproj" (default target) (3) ->
  D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_func\ta_func.vcxproj(135,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargetsMicrosoft.CPP.UpgradeFromVC60.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.


"D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" (default target) (1) ->
"D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_abstract\ta_abstract.vcxproj" (default target) (4) ->
  D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_abstract\ta_abstract.vcxproj(128,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargetsMicrosoft.CPP.UpgradeFromVC60.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.


"D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_lib.sln" (default target) (1) ->
"D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_libc\ta_libc.vcxproj" (default target) (5) ->
  D:\Personal-Projects\Traders\node_modules\talib\src\lib\make\csr\windows\msbuild\ta_libc\ta_libc.vcxproj(136,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargetsMicrosoft.CPP.UpgradeFromVC60.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

    1 Warning(s)
    4 Error(s)

Time Elapsed 00:00:00.29


(base) D:\Personal-Projects\Traders\node_modules\talib>if not defined npm_config_node_gyp (node "C:\Users\tvdar\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure )  else (node "C:\Users\tvdar\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" configure )

(base) D:\Personal-Projects\Traders\node_modules\talib>if not defined npm_config_node_gyp (node "C:\Users\tvdar\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" build )  else (node "C:\Users\tvdar\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" build )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  talib.cpp
  win_delay_load_hook.cc
..\src\talib.cpp(85): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\Personal-Projects\Traders\node_modules\talib\build\talib.vcxproj]
  D:\Personal-Projects\Traders\node_modules\nan\nan.h(1742): note: see declaration of 'Nan::Callback::Call'
..\src\talib.cpp(95): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\Personal-Projects\Traders\node_modules\talib\build\talib.vcxproj]    
  D:\Personal-Projects\Traders\node_modules\nan\nan.h(1742): note: see declaration of 'Nan::Callback::Call'
..\src\talib.cpp(546): warning C4996: 'Nan::Callback::Call': was declared deprecated [D:\Personal-Projects\Traders\node_modules\talib\build\talib.vcxproj]
  D:\Personal-Projects\Traders\node_modules\nan\nan.h(1742): note: see declaration of 'Nan::Callback::Call'
LINK : fatal error LNK1181: cannot open input file '..\src\lib\lib\ta_libc_csr.lib' [D:\Personal-Projects\Traders\node_modules\talib\build\talib.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\tvdar\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tvdar\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd D:\Personal-Projects\Traders\node_modules\talib
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok
npm WARN traders@1.0.0 No description
npm WARN traders@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! talib@1.1.3 install: `node ./src/lib/build.js && node-gyp configure && node-gyp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the talib@1.1.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tvdar\AppData\Roaming\npm-cache\_logs\2020-07-21T01_57_11_479Z-debug.log
```

If anyone can help me fix this issue, I'd really appreciate it. Thank you so much.

**Comment by amangqq** [comment]
谁点赞的，解决了吗？

**Comment by Ovodo** [comment]
Just make sure you downlaod Windows Build tools 2015 version and then try again. You can download this manually from here https://my.visualstudio.com/Downloads?q=visual%20studio%202015&wt.mc_id=o~msft~vscom~older-downloads.

**Comment by alangustavo** [comment]
Hi Guys!

I try to install in my Win 2010 or Win2010 with Ubuntu-22.04 WSL, but i have this problem
npm install talib
npm ERR! code 1
npm ERR! path \\wsl.localhost\Ubuntu-22.04\home\alangustavo\mybot\node_modules\talib
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node ./src/lib/build.js && node-gyp configure && node-gyp build
npm ERR! '\\wsl.localhost\Ubuntu-22.04\home\alangustavo\mybot\node_modules\talib'
npm ERR! CMD.EXE foi iniciado tendo o caminho acima como pasta atual.
npm ERR! N�o h� suporte para caminhos UNC. Padronizando para pasta do Windows.
npm ERR! node:internal/modules/cjs/loader:1080
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'C:\Windows\src\lib\build.js'
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:922:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
npm ERR!     at node:internal/main/run_main_module:23:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }
npm ERR!
npm ERR! Node.js v18.18.0
