### ISSUE TITLE
Cannot install TALIB on Raspberry (ARM) with Ubuntu 64bit

### ISSUE THREAD

**Issue by strawberry-code** [oransel/node-talib#87]
Trying to install talib in Raspberry Pi 3 (ARM) with Ubuntu 20 64bit I get:

```
~/zenbot$ npm i

> talib@1.1.3 install /home/ubuntu/zenbot/node_modules/talib
> node ./src/lib/build.js && node-gyp configure && node-gyp build

building talib functions...
cd ta_common; make
make[1]: Entering directory '/home/ubuntu/zenbot/node_modules/talib/src/lib/make/csr/linux/g++/ta_common'
gcc -c -pipe -fPIC -Wall -W -O2 -fno-strict-aliasing -DTA_SINGLE_THREAD  -I../../../../../src/ta_common -I../../../../../include -o ../../../../../temp/csr/ta_global.o ../../../../../src/ta_common/ta_global.c
make[1]: Leaving directory '/home/ubuntu/zenbot/node_modules/talib/src/lib/make/csr/linux/g++/ta_common'
 /usr/lib/gcc/aarch64-linux-gnu/10/cc1: symbol lookup error: /usr/lib/gcc/aarch64-linux-gnu/10/cc1: undefined symbol: _ZNSt13bad_exceptionD1Ev
make[1]: *** [Makefile:96: ../../../../../temp/csr/ta_global.o] Error 1
make: *** [Makefile:19: ta_common] Error 2

make: Entering directory '/home/ubuntu/zenbot/node_modules/talib/build'
  CXX(target) Release/obj.target/talib/src/talib.o
/usr/lib/gcc/aarch64-linux-gnu/10/cc1plus: symbol lookup error: /usr/lib/gcc/aarch64-linux-gnu/10/cc1plus: undefined symbol: _ZNSt13bad_exceptionD1Ev
make: *** [talib.target.mk:109: Release/obj.target/talib/src/talib.o] Error 1
make: Leaving directory '/home/ubuntu/zenbot/node_modules/talib/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 5.8.0-1006-raspi
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v14.15.0/bin/node" "/home/ubuntu/.nvm/versions/node/v14.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/ubuntu/zenbot/node_modules/talib
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
```

Can anyone help?

**Comment by oransel** [comment]
Looks like a cross compilation issue on ARM. I have not tested with Raspberry Pi yet.

**Comment by Matejz90** [comment]
On rpi this work (buster, node8):

npm install talib@1.0.2
